const STORAGE_KEY='gerador_itens_v3_hist';const form=document.getElementById('itemForm');const statusEl=document.getElementById('status');const resultadoEl=document.getElementById('resultado');const historicoEl=document.getElementById('historico');const ucEl=document.getElementById('uc');const competenciaEl=document.getElementById('competencia');const habilidadeEl=document.getElementById('habilidade');const conhecimentoEl=document.getElementById('conhecimento');const normaEl=document.getElementById('normaTecnica');let currentItem=null;
function init(){loadUCs();ucEl.addEventListener('change',refreshDependentFields);form.addEventListener('submit',onSubmit);document.getElementById('limparBtn').addEventListener('click',()=>{form.reset();refreshDependentFields();});document.getElementById('printBtn').addEventListener('click',()=>window.print());document.getElementById('exportJsonBtn').addEventListener('click',exportJSON);document.getElementById('exportTxtBtn').addEventListener('click',exportTXT);document.getElementById('exportHtmlBtn').addEventListener('click',exportHTML);document.getElementById('limparHistoricoBtn').addEventListener('click',clearHistory);renderHistory();}
function loadUCs(){window.COURSE_DATA.ucs.forEach(uc=>{const opt=document.createElement('option');opt.value=uc.id;opt.textContent=`${uc.id} – ${uc.nome}`;ucEl.appendChild(opt);});ucEl.value='UC7';refreshDependentFields();}
function getSelectedUC(){return window.COURSE_DATA.ucs.find(uc=>uc.id===ucEl.value)||window.COURSE_DATA.ucs[0];}
function refillSelect(selectEl,items){selectEl.innerHTML='';items.forEach(item=>{const opt=document.createElement('option');opt.value=item;opt.textContent=item;selectEl.appendChild(opt);});}
function refreshDependentFields(){const uc=getSelectedUC();competenciaEl.value=uc.competencia;refillSelect(habilidadeEl,uc.habilidades);refillSelect(conhecimentoEl,uc.conhecimentos);refillSelect(normaEl,uc.normas);}
function setStatus(text,isError=false){statusEl.textContent=text;statusEl.style.color=isError?'#ef4444':'#38bdf8';}
function buildPayload(){return{data:new Date().toLocaleString('pt-BR'),fichaId:document.getElementById('fichaId').value.trim()||`AUTO-${Date.now()}`,elaborador:document.getElementById('elaborador').value.trim()||'Não informado',uc:ucEl.value,uc_nome:getSelectedUC().nome,competencia:competenciaEl.value,habilidade:habilidadeEl.value,conhecimento:conhecimentoEl.value,bloom_nivel:document.getElementById('bloomNivel').value,bloom_processo:document.getElementById('bloomProcesso').value,bloom_conhecimento:document.getElementById('bloomConhecimento').value,dificuldade:document.getElementById('dificuldade').value,tipo_conhecimento:document.getElementById('tipoConhecimento').value,norma_tecnica:normaEl.value,observacoes:document.getElementById('observacoes').value.trim()};}

function renderItem(item){resultadoEl.classList.remove('vazio');resultadoEl.innerHTML=`<div class="result-block"><h3>Dados-base</h3><p><strong>ID:</strong> ${escapeHtml(item.fichaId)}<br><strong>Elaborador:</strong> ${escapeHtml(item.elaborador)}<br><strong>UC:</strong> ${escapeHtml(item.uc)} – ${escapeHtml(item.uc_nome)}<br><strong>Competência:</strong> ${escapeHtml(item.competencia)}<br><strong>Habilidade:</strong> ${escapeHtml(item.habilidade)}<br><strong>Conhecimento:</strong> ${escapeHtml(item.conhecimento)}<br><strong>Bloom:</strong> ${escapeHtml(item.bloom_nivel)} | ${escapeHtml(item.bloom_processo)} | ${escapeHtml(item.bloom_conhecimento)}<br><strong>Dificuldade:</strong> ${escapeHtml(item.dificuldade)}<br><strong>Norma:</strong> ${escapeHtml(item.norma_tecnica)}</p></div><div class="result-block"><h3>Análise metodológica</h3><p>${escapeHtml(item.analise)}</p></div><div class="result-block"><h3>Situação-estímulo</h3><p>${escapeHtml(item.situacao)}</p></div><div class="result-block"><h3>Comando</h3><p>${escapeHtml(item.comando)}</p></div><div class="result-block alt-list"><h3>Alternativas</h3><p><strong>A)</strong> ${escapeHtml(item.alternativas.A)}</p><p><strong>B)</strong> ${escapeHtml(item.alternativas.B)}</p><p><strong>C)</strong> ${escapeHtml(item.alternativas.C)}</p><p><strong>D)</strong> ${escapeHtml(item.alternativas.D)}</p></div><div class="result-block"><h3>Gabarito</h3><p><strong>${escapeHtml(item.gabarito)}</strong></p></div><div class="result-block just-list"><h3>Justificativas</h3><p><strong>A)</strong> ${escapeHtml(item.justificativas.A)}</p><p><strong>B)</strong> ${escapeHtml(item.justificativas.B)}</p><p><strong>C)</strong> ${escapeHtml(item.justificativas.C)}</p><p><strong>D)</strong> ${escapeHtml(item.justificativas.D)}</p></div><div class="result-block"><h3>Validação metodológica</h3><div class="validation-grid">${Object.entries(item.validacao).map(([k,v])=>`<div class="validation-item"><strong>${escapeHtml(k)}</strong><br><span class="${v?'ok':'fail'}">${v?'Atende':'Não atende'}</span></div>`).join('')}</div></div>`;}
function getHistory(){return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');}
function saveHistory(item){const list=[item,...getHistory()].slice(0,20);localStorage.setItem(STORAGE_KEY,JSON.stringify(list));}
function clearHistory(){localStorage.removeItem(STORAGE_KEY);renderHistory();}
function renderHistory(){const list=getHistory();historicoEl.innerHTML=list.length?list.map(item=>`<div class="history-card"><strong>${escapeHtml(item.fichaId)}</strong> — ${escapeHtml(item.habilidade)}<div class="meta">${escapeHtml(item.data)} • ${escapeHtml(item.uc)} • ${escapeHtml(item.dificuldade)}</div></div>`).join(''):'<p class="meta">Nenhum item salvo ainda.</p>';}
function buildFichaText(item){return`FICHA AVALIATIVA — ${item.fichaId}\nData: ${item.data}\nElaborador: ${item.elaborador}\nUnidade Curricular / Módulo: ${item.uc} – ${item.uc_nome}\nCompetência: ${item.competencia}\nHabilidade: ${item.habilidade}\nConhecimento relacionado: ${item.conhecimento}\nTipo do item: Múltipla escolha — 4 opções\nBloom: ${item.bloom_nivel} | ${item.bloom_processo} | ${item.bloom_conhecimento}\nDificuldade: ${item.dificuldade}\nNorma técnica: ${item.norma_tecnica}\n\nANÁLISE METODOLÓGICA\n${item.analise}\n\nSITUAÇÃO-ESTÍMULO\n${item.situacao}\n\nCOMANDO\n${item.comando}\n\nALTERNATIVAS\nA) ${item.alternativas.A}\nB) ${item.alternativas.B}\nC) ${item.alternativas.C}\nD) ${item.alternativas.D}\n\nGABARITO\n${item.gabarito}\n\nJUSTIFICATIVAS\nA) ${item.justificativas.A}\nB) ${item.justificativas.B}\nC) ${item.justificativas.C}\nD) ${item.justificativas.D}\n\nVALIDAÇÃO METODOLÓGICA\n${Object.entries(item.validacao).map(([k,v])=>`- ${k}: ${v}`).join('\n')}`;}
function downloadFile(filename,content,type){if(!currentItem)return setStatus('Gere um item antes de exportar.',true);const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function exportTXT(){downloadFile(`${currentItem.fichaId}.txt`,buildFichaText(currentItem),'text/plain;charset=utf-8');}
function exportJSON(){downloadFile(`${currentItem.fichaId}.json`,JSON.stringify(currentItem,null,2),'application/json');}
function exportHTML(){const html=`<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>${currentItem.fichaId}</title></head><body><pre>${escapeHtml(buildFichaText(currentItem))}</pre></body></html>`;downloadFile(`${currentItem.fichaId}.html`,html,'text/html;charset=utf-8');}
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s]));}
init();
